services:
  db-course:
    image: "mongo:7.0.12-rc1-jammy"
    container_name: "db-course-health"
    ports:
      - "27025:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo-db
      - MONGO_INITDB_ROOT_PASSWORD=mongo-db-28000
    restart: always
    healthcheck:
      test: echo 'db.runCommand({find:"db_course.chanchhaya"}).ok' | mongosh --authenticationDatabase admin --host localhost -u mongo-db -p mongo-db-28000 admin --quiet | grep -q 1
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 20s
    volumes:
      - course_mongodb_data_vol:/data/db/
      - course_mongodb_log_vol:/var/log/mongodb/
    networks:
      - course_mongodb_net
  api-course:
    build: .
    image: "api-course"
    container_name: "api-course-health"
    ports:
      - "7072:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      db-course:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 512m
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - course_mongodb_net

volumes:
  course_mongodb_data_vol:
  course_mongodb_log_vol:

networks:
  course_mongodb_net:
