spring:
  application:
    name: test1

  profiles:
    active: dev

  data:
    mongodb:
      host: ${DB_HOST}
      port: ${DB_PORT}g
      database: ${DB_NAME}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      authentication-database: ${AUTHENTICATION-DATABASE}

springdoc:
  swagger-ui:
    path: /
minio:
  url: ${MINIO_URL}
  secret-key: ${MINIO_SECRETE_KEY}
  bucket-name: ${MINIO_BUCKET}
  access-key: ${MINIO_ACCESS_KEY}

media:
  #media endpoint
  end-point: ${MEDIA_ENDPOINT}
  #the host that handle show image
  base-uri: ${MEDIA_BASE_URI}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always

---
spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      uri: mongodb://docker-db:docker-db-27025@db-course-health:27025/
      database: db_course
      authentication-database: admin
