
DB_USERNAME: mongo-db
DB_PASSWORD: mongo-db-28000
DB_HOST: 68.183.187.158
DB_PORT: 28000
DB_NAME: testing_product_and_upload_file
AUTHENTICATION-DATABASE: admin

MINIO_URL: http://68.183.187.158:9000
MINIO_ACCESS_KEY: MBpTLbpa4UvX9CpIarmI
MINIO_SECRETE_KEY: VNre5RbaZyIBteYy2bxujE3jiCJi9uIbWDtbCYq9
MINIO_BUCKET: product-testing-api-and-file

MEDIA_BASE_URI: http://68.183.187.158:7000
MEDIA_ENDPOINT: /api/v1/medias

#MEDIA_BASE_URI: http://127.0.0.1:8080